
 
 
<head> 
<meta property="og:title" content="Buick - NCAA Team Badges" /> 
<meta property="og:description" content="Take notice, NCAA fans!  Choose your team and show your spirit by posting a fan badge!" /> 
<meta property="og:site_name" content="Buick - NCAA Team Badges" /> 
<meta property="og:image" content="http://174.143.153.39/buick/90x90_BUICK_NCAA.jpg" /> 
<meta property="og:type" content="website" /> 
<meta property="og:url" content="http://apps.facebook.com/ncaabadges/" /> 
</head> 
 
<!-- 
CSS 
--> 
<style> 
body {
  font-family:"lucida grande",tahoma,verdana,arial,sans-serif;
  background: url('ncaabadges-index3.png') no-repeat fixed;
  padding:0px;
  margin:0px;
}
 
.wall {
  background-image: url("http://momentusmedia.com/publisher/static/img/offer/felt-background.png");
  width:750px;
  height:500px;
  overflow-y:scroll;
  color: #9287AF;
  text-shadow: 0px 1px 0px #ccc;
  line-height:24px;
  padding:5px;
}

.bottom {
  background-image: url("http://174.143.153.39/wreath/new/bottom.png");
  width:720px;
  height: 199px;
  margin-top:-85px;
  z-index:1000;
  position:absolute;
  top:565px;
  left:15px;
}

.add-button {
  vertical-align:middle;
}
</style> 
 
 
 
 
 
 
<!-- 
Javascript 
--> 
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script> 
<script> 
var FB_APP_ID = '210860405620661';
var FB_APP_URL = 'http://apps.facebook.com/memorialday/';

$(document).ready(function(){

 });
 
</script>
<body>
<img src="logo.png"/>
<br>
Honor our fallen veterans by writing a name on the memorial or by laying a wreath.
<br>
<br>
<div class="wall">
<a href=#><img class="add-button" src="button.png"></a>
SP4 GERALD L AADLAND	SGT JAMES DOWNING AALUND	A1C DANIEL LAWRENCE AAMOLD
LCPL JAMES RAYMOND AARDE	SP4 CHARLES EDWARD AARON	PFC EUGENE ALLEN AARON
PVT MICHAEL PETER AARON	CPT RICHARD ALAN AARON	SP4 THOMAS MILTON AARON Jr
PFC WILLIAM F AARONSON IV	LCPL DAVID KIM AASEN	SGT JOSE GENE ABARA
CPL RICHARD CLARK ABBATE	SGT ROSARIO RUSSEL ABBATE	SGT JOHN BENJAMIN ABBATEMARCO
PFC GERALD ROBERT ABBENHAUS Jr	PFC DONALD PAUL ABBIE	SP4 CARROLL DAVID ABBOTT
SP5 DAVID FRANCIS ABBOTT	PFC DENIS EUGENE ABBOTT	PFC EDWARD DONALD ABBOTT
SFC GUY FRANCIS ABBOTT	PFC HAROLD WAYNE ABBOTT	PVT JAMES EDWARD ABBOTT
CPL JAMES MICHAEL ABBOTT	SP6 JAMES TERRY ABBOTT	CAPT JOHN ABBOTT
1LT JOHN WILLIAM ABBOTT	PFC PAUL DENNIS ABBOTT	CPL RAYMOND LAWRENCE ABBOTT
PFC ROBERT ESTEN ABBOTT Jr	MAJ ROBERT WILLIAM ABBOTT	1LT STEVEN GLENN ABBOTT
PVT TERRY MICHAEL ABBOTT	PFC WALLACE ADRION ABBOTT	PVT BRUCE ALLYN ABDELLAH
CPL GHALIB AHMED ABDULLAH	CPL ARNOLD GORDON ABEL	CPT CHARLES SEABORN ABEL
CAPT CHARLES FREDERICK ABENE	1LT DANIEL OWEN ABERNATHY	SP5 JIMMY EDD ABERNATHY
MAJ ROBERT LLOYD ABERNATHY	SP4 ROBERT WILLIAM ABERNATHY	PFC REGINALD JOE ABERNETHY
CPT WILLIAM FORMAN ABERNETHY	PFC GEORGE WAYNE ABEY	PFC ERNEST ABEYTA
CPL JERRY DELBERT ABEYTA	LCPL TONY GENEVEVO ABEYTA	PFC ROBERT THOMAS ABINA
SSG DAVID FLOYD ABLE	SP4 JAMES LYNN ABLER	SFC ELMER ROBERT LEE ABLES Jr
LCPL KENNETH RONALD ABMEYER	LCPL CARL EDWARD ABNER	SP4 DANIEL THOMAS ABNEY Jr
PFC JANIS ABOLINS	SP4 RICHARD D ABOLTIN	PFC ARLEY GEORGE ABRAHAM
SGT JAMES JOSEPH ABRAHAM	SGT PAUL HAROLD ABRAHAM	CPL PAUL LEONARD ABRAHAM
CPL ROOSEVELT ABRAHAM Jr	CPL GARY LEE ABRAHAMSON	SSG JAMES HENRY ABRAM
1LT ARTHUR JOHN ABRAMOFF	CPT LEO BERT ABRAMOSKI	LCPL JOHN ALAN ABRAMS
LT JOHN LEON ABRAMS	COL LEWIS HERBERT ABRAMS	SSG SAMUEL ABRAMS Jr
PFC TIMOTHY C ABRAMS Jr	WO ANDREW JOHN ABRAMSON	CPL MIGUEL A ABREU-BATISTA Jr
SP4 ANTHONY JOSEPH ABRUZESE	PFC ROBERT ALEXANDER ABRUZESE	PFC MICHAEL JOHN ABRUZZESA Jr
SGT WILLIAM WALLACE ABSHEAR	SGT RICHARD FRANKLIN ABSHIRE	PFC JAMES ESTUS ABSTON Jr
SSG ROBERT JOSEPH ACALOTTO	SP5 PEPITO RIVERA ACERET	PFC HECTOR SANTOS ACEVEDO
LCPL RICHARD JOSEPH ACEVEDO	SP4 ROBERTO ACEVEDO	SP4 ANGEL LUIS ACEVEDO-MILLAN
MAJ RAFAEL ACEVEDO-RECHANI	LCPL ROBERT JOHN ACHAS	CAPT ROBERT PAUL ACHER Jr
PFC CHARLES RALPH ACHESON	SGT EDDIE ACHICA	LCPL TIMOTHY EUGENE ACHISON
PFC LEEVERNE RICHARD ACHOE	PFC TERRENCE WILLIAM ACHOR	PFC DAVID PAUL ACHORD
LCPL JAMES PATRICK ACHTERHOFF	SA HERMAN CAROL ACKER	PFC ODELL BERNARD PATE ACKER
CPL BILL R ACKERMAN	SGT DANIEL LEVERNE ACKERMAN	PFC DAVID ALAN ACKERMAN
PFC DAVID FOLEY ACKERMAN	WO DENNIS CARLTON ACKERMAN	CPT EDWIN ARTHUR ACKERMAN Jr
PFC JAMES CARROLL ACKERMAN Jr	PFC JOHN ROBERT ACKERMAN	EO3 LEONARD MICHAEL ACKERMAN
CPL MAXIE EDWARD ACKERMAN	PFC REX WILLIAM ACKERMAN	SSG ROGER CARL HENRY ACKERMAN
SGT THOMAS ALAN ACKERMAN	SFC VENCEN ACKERSON	SGT GERALD LEVIE ACKLEY
PFC WALTER JAMES ACKWOOD	SSG EWELL EDGEL ACORD	PFC DANIEL ACOSTA
SD1 GERMAN PORTACIO ACOSTA	LCPL JAMES ARTHUR ACOSTA Jr	SSGT JESSE RODRIQUEZ ACOSTA
PFC JOHN MICHAEL ACOSTA	SP4 JOHN WAYNE ACOSTA	CPL JOSE FRANCISCO ACOSTA
LCPL LOYD DEAN ACOSTA	SSG HUMBERTO ACOSTA-ROSARIO	MAJ LAWRENCE DALE ACRE
SGT BILLIE RAY ACREE	PFC ROGER LEE ACREE	HN DAVID AUGUST ACTON
SP4 GERALD RICHARD ACTON	PFC MARION FRANKLIN ACTON	GYSGT TOM PERRY ACTON
SP4 EDDIE DUANE ACUFF	LCPL EDGAR ACUNIA	SMSGT THOMAS YUJI ADACHI
CPL DALLAS TYLER ADAIR Jr	PFC HARVEY GENE ADAIR	MAJ SAMUEL YOUNG ADAIR Jr
SSG THURMAN ADAIR	SGT WILLIAM MICHAEL ADAIR	CPL LEO JOE ADAKAI
PFC BARRY L ADAM	SP4 HOSEA DENNIS ADAM	SMSGT JOHN QUINCY ADAM
SFC RAYMOND ALVIN ADAM	SGT ARTHUR PINA ADAME	PFC GILBERT JIMMIE ADAME
LCPL SANTIAGO DEJOYAS ADAMES Jr	SP4 IAN WILLIAM ADAMITZ	SN RICHARD CHARLES ADAMO
CPL ROWLAND JOSEPH ADAMOLI	BUH3 ARTHUR LLOYD ADAMS Jr	PVT AUGUSTUS ADAMS
CPL BERT MORRIS ADAMS III	PFC BOYED TIMOTHY ADAMS	SFC CARL TURNER ADAMS
BGEN CARROLL EDWARD ADAMS Jr	SP4 CHARLES HENRY ADAMS	SP4 CHARLES WESLEY ADAMS
SGT CLARENCE CLIFTON ADAMS	SSG CLARENCE MATTUE ADAMS	CPL DARRIUS WAYNE ADAMS
WO DAVEY MARLIN ADAMS	SP4 DAVID LEE ADAMS	PFC DAVID LEE ADAMS
CPL DAVID VERNON ADAMS	PFC DENNIS MICHAEL ADAMS	PFC DONALD BEN ADAMS Jr
PFC DWANE LONNIE ADAMS	PFC DWIGHT LEE ADAMS	FN EDDIE MARTIN ADAMS
SWF2 EDWARD CODY ADAMS	PFC EMMITT COLON ADAMS	SGT ERHARD JIMMIE ADAMS
PFC FRANK DAVID ADAMS	CAPT FRANK HOUSTON ADAMS	SGT GEORGE DAYTON ADAMS
LCPL GEORGE FRANCIS ADAMS	SP4 GEORGE GAYRAL ADAMS	CPT GEORGE HARTWELL ADAMS
SGT GILLES DAVID ADAMS	CWO GLENN ARTHUR ADAMS	SSG HARLAN FLOYD ADAMS
SP5 HERBERT NORMAN ADAMS	MAJ HUGHIE DARELL ADAMS	1LT JAMES CLARENCE ADAMS
MAJ JAMES CONRAD ADAMS	SP4 JAMES EDWARD ADAMS	PFC JAMES HENRY ADAMS
SSG JAMES LINDELL ADAMS	SP4 JAMES RICHARD ADAMS	2LT JAMES ROBERT ADAMS
1LT JERRY DEAN ADAMS	PFC JESSE LEWIS ADAMS	CPT JOHN K ADAMS
CPL JOHN LOUIS ADAMS	SSG JOHN ROBERT ADAMS	LCPL JOHN TERRY ADAMS
CAPT JOHN WILBURN ADAMS	SGT JOSEPH ADAMS	SN JOSEPH BOYCE ADAMS
CPL KENNETH STANLEY ADAMS	PFC KENNEY MILTON ADAMS Jr	SP4 LARRY ADAMS
LCPL LARRY EARL ADAMS	1LT LEE AARON ADAMS	PFC LEE CHESTER ADAMS
2LT LEE SCOTT ADAMS	SP4 LEON HENRY ADAMS	SGT MERRITT ADAMS
PFC MICHAEL DRUE ADAMS	SGT MICHAEL EDWARD ADAMS	CPL MICHAEL EUGENE ADAMS
CAPT MICHAEL THOMAS ADAMS	SSG NEIL ADAMS Jr	SGT NORMAN EDWARD ADAMS
SSGT OLEY NEAL ADAMS	SP4 PAUL EDWIN ADAMS	SGT PAUL VERNON ADAMS
LCPL PETER ROBERT ADAMS	CPL PHILIP FRANCIS ADAMS	SP4 PHILIP J ADAMS
PVT PHILLIP CURTIS ADAMS	SP4 RAYMOND SPENCER ADAMS	SP4 RICHARD LEE ADAMS
SSG RICHARD LYLE ADAMS	LCPL RICKY FAY ADAMS	1LT ROBERT JAMES ADAMS
2LT ROBERT LEE ADAMS Jr	SGT ROBERT LELAND ADAMS	LCPL ROGER DEAN ADAMS
SGT RONALD M ADAMS	PFC RONALD WYATT ADAMS	SGT RONNIE LEE ADAMS
PVT ROSCOE DAVID ADAMS	TSGT ROYCE HORACE ADAMS	PFC RUSSELL BYRD ADAMS
PFC RUSSELL LEE ADAMS	CMSGT SAMUEL ADAMS	SSG SPENCER ADAMS
CAPT STANLEY LEE ADAMS	PFC STEADMON ADAMS	PFC STEPHEN HAMILTON ADAMS
MSGT STEVEN HAROLD ADAMS	PFC STEVEN JACK ADAMS	PFC TED WANE ADAMS
CPL TERRANCE DEAN ADAMS	CPL TERRY LEE ADAMS	1LT THOMAS BURL ADAMS
SN THOMAS EDWARD ADAMS	WO THOMAS EDWARD ADAMS	PFC WALTER LEE ADAMS
SGT WAYNE ROGER ADAMS	CPL WILLIAM ADAMS Jr	SGT WILLIAM CARL ADAMS
MAJ WILLIAM EDWARD ADAMS	SGT WILLIAM ERNEST ADAMS	SP5 WILLIAM J ADAMS
PFC WILLIAM JAMES ADAMS	PFC WILLIAM OTHELLO ADAMS Jr	CPL WILLIAM RAYMOND ADAMS
CPL WILLIAM RICHARD ADAMS	PFC WOODROW WILLIAM ADAMS	SP4 DENNIS JAMES ADAMSKI
2LT DONALD BRUCE ADAMSON	PFC FRANK LESLIE ADAMSON	SP4 LARRY ONEAL ADAMSON
PFC RICHARD DONALD ADAY	SP4 ROBERT LEE ADAY	PFC BILLY ANTHONY ADCOCK
CPL RICHARD LYNN ADCOCK	LCPL RONNIE DARNELL ADCOX	1LT KYLE ASHCOM ADDAIR
HN FRANK PAUL ADDICE	SP4 ROYCE LEE ADDINGTON	LCPL ZACK TAYLOR ADDINGTON
SSG BILLY WAYNE ADDIS	SP4 FRANCIS RAY ADDIS	SSG JERRY LEROY ADDIS
WO HARVEY CHARLES ADDISON	LCPL JOHN EDWARD ADDISON	SP5 O'NEAL ADDISON
PFC RICHARD EDWARD ADDISON Jr	SP4 JOHN JOSEPH ADDUCI	SGT DWIGHT I ADE
SD3 RESTITUTO POBLETE ADENIR	SGT HENRY LESTER ADERHOLT	LCPL ARNOLD ALVIN ADES
LCPL WILLIE HOWARD ADGER	PFC ALVIN ADIKAI Jr	SP4 RICHARD ADIUTORI
SGT BOBBY RAY ADKINS	SP4 CARL EDWARD ADKINS	PFC CHARLES LELAND ADKINS
SFC CHARLES LEROY ADKINS	PFC DONALD WAYNE ADKINS	SP4 HENRY DALE ADKINS
CPL JAMES DALE ADKINS	CPL JOHN ADKINS	SGT KENNETH DALE ADKINS
PFC LLOYD MARVIN ADKINS Jr	PR2 MARVIN JARRELL ADKINS	SP4 MICHAEL DUANE ADKINS
PFC NORMAN DALE ADKINS	PFC RONALD EUGENE ADKINS	CPL TERRY LEE ADKINS
BM1 WAYNE LAWRENCE ADKINS	SP4 CARL ELMUS ADKISON	SSGT JAMES WILLIE ADKISSON
MSG HENRY ADLER	SSG TOM ROBERT ADLER	SP4 WOODROW DENNIS ADLER
LCPL LARRY EUGENE ADOLF	1LT JOSEPH DANIEL ADRIAN	LCPL DAVID LEE AERTS
CWO DAVID KEITH AESCHLIMAN	CPT MARK AFFLERBACH	SP4 ANTHONY PHILIP AGAR
CPL ROBERT LEE AGAR	PVT ROWLAND NATHANIEL AGARD	SP4 TIMOTHY CHARLES AGARD
LTC FREDERIC GUSTAVE AGATHER	FTG3 DAVID MICHAEL AGAZZI	HM3 JOHN CHARLES AGEE
LCPL VINCENT JAMES AGIUS	EM3 MANOLO BRIONES AGNES	SGT JAMES WILLIAM AGNEW
LCPL JOSEPH JOHN AGRI Jr	PFC SALVATORE AGRI Jr	1LT ROBERT CHARLES AGUADO
SP4 OSCAR AGUAYO Jr	PFC MATTHEW JOHN AGUGLIARO	PFC JUAN DANIEL AGUIAR
SP4 ADOLFO AGUILAR	PFC ARMANDO AGUILAR	PVT ARNOLD AGUILAR
LTC DOMINGO IGNACIO AGUILAR	SP4 JAMES DANIEL AGUILAR	SGT MIKE JOHN AGUILAR
CPL NICK ALFRED AGUILAR Jr	SP4 OSCAR AGUILAR	PFC PEDRO RAMIREZ AGUILAR
LCPL REIMUNDO AGUILAR	SP4 ROBERT AGUILAR	PFC RUDOLPH RENE AGUILAR
PFC DANIEL AGUILERA	TSGT FELIZARDO CUENCA AGUILLON	SP4 JOSE JESUS AGUILLON
SSG ARTHUR CECILIO AGUIRRE	LCPL CARLOS CRUZ AGUIRRE	SGT FIDEL JOE AGUIRRE
HM3 FILBERTO AGUIRRE Jr	CPL GEORGE AGUIRRE	PFC JOSEPH ANTHONY AGUIRRE
PFC RAYMOND AGUIRRE	PSGT JOSE QUINATA AGUON	SP5 WILLIAM JUNIOR AHART
LCPL BRIAN PAUL AHERN	SP4 JOHN BERNARD AHERN	SP4 RAYMOND JOSEPH AHERN Jr
SP5 ROBERT PAUL AHERN	SGT TONY AHINZOW	SGT THOMAS OLIVER AHLBERG
PFC ALAN PAUL AHLFIELD	2LT HEINZ AHLMEYER Jr	PFC ROBERT ERNEST AHLSTROM
CPT WILLIAM JOHN AHLUM	1LT WILLIAM C AHOUSE	SP4 DENNIS LYNN AHRENDSEN
PFC JAMES JOHN AHRENS	SP5 RUSSELL GEORGE AHRENS	SFC ABRAHAM KAALELE AHUNA
LCDR HARVEY CHADWICK K AIAU	PFC ELDRIDGE CHARLES AIGELDINGER	PFC DAVID ROSS AIKEN
SP4 LARRY DELARNARD AIKEN	PFC LEROY BENJAMIN AIKEN	SGT WILLIAM LESLIE AIKEN
SGT TIMOTHY WAYNE AIKEY	CPT GEORGE LEE AIKIN	PFC WILLIAM EUGENE AILES
SSGT DAVID EMIL AILI	SP4 JIM LAMARR AILSTOCK Jr	PFC JOHN MATHEW AINSWORTH Jr
SP5 KENNETH JOHN AINSWORTH	SP4 GEORGE VERNON AIREY Jr	SGT WILLIAM CLARK AIRLIE
SGT DEAN L AITKEN	PFC GERALD DAVID AITON	CPL JOSEPH ROBERT AJSTER
SFC ALBERT KAIWI AKAMU	SP5 FRANKLIN RANDOLPH AKANA	PFC HOMER LEE AKE Jr
LCPL HOWARD DAVID AKEHURST	SGT RICHARD LOUIS AKEL	HN JEFFREY SCOTT AKER
PFC DENNIS AKERLEY	LCPL ARVEL DEWIT AKERS	SP4 DENNIS OWEN AKERS
LCPL E G AKERS Jr
</div>
<div class="bottom"></div>
</body> 
 
 
 
 
 
<!-- 
Facebook stuff 
--> 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({appId: '210860405620661', status: true, cookie: true,
             xfbml: true})
    window.setTimeout(function() {
      FB.Canvas.setAutoResize();
    }, 250);                  
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/en_US/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>